config/routes.rb
Rails.application.routes.draw do
  resources :commentars
  resources :artikels
  resources :kommentares
  resources :posts
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
end

app/models/artikel.rb
class Artikel < ApplicationRecord
    has_many :commentars
end

app/controllers/artikels_controller.rb
class ArtikelsController < ApplicationController
  before_action :set_artikel, only: %i[ show edit update destroy ]

  # GET /artikels or /artikels.json
  def index
    @artikels = Artikel.all
  end

  # GET /artikels/1 or /artikels/1.json
  def show
    @artikel_commentars = Artikel.find(params[:id]).commentars
  end

  # GET /artikels/new
  def new
    @artikel = Artikel.new
  end

  # GET /artikels/1/edit
  def edit
  end

  # POST /artikels or /artikels.json
  def create
    @artikel = Artikel.new(artikel_params)

    respond_to do |format|
      if @artikel.save
        format.html { redirect_to artikel_url(@artikel), notice: "Artikel was successfully created." }
        format.json { render :show, status: :created, location: @artikel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artikel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artikels/1 or /artikels/1.json
  def update
    respond_to do |format|
      if @artikel.update(artikel_params)
        format.html { redirect_to artikel_url(@artikel), notice: "Artikel was successfully updated." }
        format.json { render :show, status: :ok, location: @artikel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artikel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artikels/1 or /artikels/1.json
  def destroy
    @commentars = Commentar.where(artikel_id: @artikel.id)
    @commentars.each do |commentar|
      commentar.destroy
    end
    @artikel.destroy

    respond_to do |format|
      format.html { redirect_to artikels_url, notice: "Artikel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artikel
      @artikel = Artikel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artikel_params
      params.require(:artikel).permit(:titel, :text)
    end
end

app/helpers/artikels_helper.rb
module ArtikelsHelper
end

app/views/artikels/_artikel.html.erb
<div id="<%= dom_id artikel %>">
  <p>
    <strong>Titel:</strong>
    <%= artikel.titel %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= artikel.text %>
  </p>

</div>

app/views/artikels/_form.html.erb
<%= form_with(model: artikel) do |form| %>
  <% if artikel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artikel.errors.count, "error") %> prohibited this artikel from being saved:</h2>

      <ul>
        <% artikel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titel, style: "display: block" %>
    <%= form.text_field :titel %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artikels/edit.html.erb
<h1>Editing artikel</h1>

<%= render "form", artikel: @artikel %>

<br>

<div>
  <%= link_to "Post anzeigen", @artikel %> |
  <%= link_to "Zurück zu Posts", artikels_path %>
</div>

app/views/artikels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Artikels</h1>

<div id="artikels">
  <% @artikels.each do |artikel| %>
    <%= render artikel %>
    <p>
      <%= link_to "Show this artikel", artikel %>
    </p>
  <% end %>
</div>

<%= link_to "New artikel", new_artikel_path %>

app/views/artikels/new.html.erb
<h1>New artikel</h1>

<%= render "form", artikel: @artikel %>

<br>

<div>
  <%= link_to "Back to artikels", artikels_path %>
</div>

app/views/artikels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artikel %>

<div>
  <%= link_to "Post bearbeiten", edit_artikel_path(@artikel) %> |
  <%= link_to "Hauptseite", root_path %>

  <%= button_to "Post zerstören", @artikel, method: :delete %>
</div>
<% # <p> Kommentare <p> %>
<% # render @artikel_commentars %>