config/routes.rb
Rails.application.routes.draw do
  resources :commentars
  resources :artikels
  resources :kommentares
  resources :posts
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
end

app/models/commentar.rb
class Commentar < ApplicationRecord
  belongs_to :artikel
end

app/controllers/commentars_controller.rb
class CommentarsController < ApplicationController
  before_action :set_commentar, only: %i[ show edit update destroy ]

  # GET /commentars or /commentars.json
  def index
    @commentars = Commentar.all
    @artikels = Artikel.all
  end

  # GET /commentars/1 or /commentars/1.json
  def show
    @commentar = Commentar.find params[:id]
  end

  # GET /commentars/new
  def new
    @commentar = Commentar.new
    if params[:artikel_id]
      @artikel_id = params[:artikel_id]
    else @artikel_id = ''
    end
  end

  # GET /commentars/1/edit
  def edit
    @commentar = Commentar.find params[:id]
  end

  # POST /commentars or /commentars.json
  def create
    @commentar = Commentar.new(commentar_params)

    respond_to do |format|
      if @commentar.save
        format.html { redirect_to commentar_url(@commentar), notice: "Commentar was successfully created." }
        format.json { render :show, status: :created, location: @commentar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @commentar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commentars/1 or /commentars/1.json
  def update
    respond_to do |format|
      if @commentar.update(commentar_params)
        format.html { redirect_to root_path, notice: "Commentar was successfully updated." }
        format.json { render :show, status: :ok, location: root_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @commentar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commentars/1 or /commentars/1.json
  def destroy
    @commentar.destroy

    respond_to do |format|
      format.html { redirect_to commentars_url, notice: "Commentar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commentar
      @commentar = Commentar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def commentar_params
      params.require(:commentar).permit(:artikel_id, :zeit, :text)
    end
end

app/helpers/commentars_helper.rb
module CommentarsHelper
end

app/views/commentars/_commentar.html.erb
<div id="<%= dom_id commentar %>">
  <p>
    <strong>Artikel:</strong>
    <%= commentar.artikel_id %>
  </p>

  <p>
    <strong>Zeit:</strong>
    <%= commentar.zeit %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= commentar.text %>
  </p>

</div>

app/views/commentars/_form.html.erb
<%= form_with(model: commentar) do |form| %>
  <% if commentar.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(commentar.errors.count, "error") %> prohibited this commentar from being saved:</h2>

      <ul>
        <% commentar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% @artikel_id %>
  <div>
    <%= form.label :artikel_id, style: "display: block" %>
    <%= form.number_field :artikel_id,id: :commentar_artikel_id, value:artikel_id%>
  </div>

  <div>
    <%= form.label :zeit, style: "display: block" %>
    <%= form.datetime_field :zeit, value:Time.now.strftime("%Y-%d-%m %H:%M:%S %Z") %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/commentars/edit.html.erb
<h1>Editing commentar</h1>

<%= render "form", commentar: @commentar, artikel_id: @artikel_id %>

<br>

<div>
  <%= link_to "Show this commentar", @commentar %> |
  <%= link_to "Back to commentars", commentars_path %>
</div>

app/views/commentars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Commentars</h1>

<div id="commentars">
  <% @commentars.each do |commentar| %>
    <%= render commentar %>
    <p>
      <%= link_to "Show this commentar", commentar %>
    </p>
  <% end %>
</div>

<%= link_to "New commentar", new_commentar_path %>

app/views/commentars/new.html.erb
<h1>New commentar</h1>

<%= render "form", commentar: @commentar, artikel_id: @artikel_id %>

<br>

<div>
  <%= link_to "Back to commentars", commentars_path %>
</div>

app/views/commentars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @commentar %>

<div>
  <%= link_to "Kommentar bearbeiten", edit_commentar_path(@commentar, :artikel_id => @commentar.artikel.id) %> |
  <%= link_to "Hauptseite", root_path %>

  <%= button_to "Kommentar zerstören", @commentar, method: :delete %>
</div>