config/routes.rb
Rails.application.routes.draw do
  resources :commentars
  resources :artikels
  resources :kommentares
  resources :posts
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
end

app/models/kommentare.rb
class Kommentare < ApplicationRecord
  belongs_to :post
  has_one :post
end

app/controllers/kommentares_controller.rb
class KommentaresController < ApplicationController
  before_action :set_kommentare, only: %i[ show edit update destroy ]

  # GET /kommentares or /kommentares.json
  def index
    @kommentares = Kommentare.all
    
  end

  # GET /kommentares/1 or /kommentares/1.json
  def show
  end

  # GET /kommentares/new
  def new
    @kommentare = Kommentare.new
  end

  # GET /kommentares/1/edit
  def edit
  end

  # POST /kommentares or /kommentares.json
  def create
    @kommentare = Kommentare.new(kommentare_params)

    respond_to do |format|
      if @kommentare.save
        format.html { redirect_to kommentare_url(@kommentare), notice: "Kommentare was successfully created." }
        format.json { render :show, status: :created, location: @kommentare }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kommentare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kommentares/1 or /kommentares/1.json
  def update
    respond_to do |format|
      if @kommentare.update(kommentare_params)
        format.html { redirect_to kommentare_url(@kommentare), notice: "Kommentare was successfully updated." }
        format.json { render :show, status: :ok, location: @kommentare }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kommentare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kommentares/1 or /kommentares/1.json
  def destroy
    @kommentare.destroy

    respond_to do |format|
      format.html { redirect_to kommentares_url, notice: "Kommentare was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kommentare
      @kommentare = Kommentare.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kommentare_params
      params.require(:kommentare).permit(:posts_id, :zeit, :text)
    end
end

app/helpers/kommentares_helper.rb
module KommentaresHelper
end

app/views/kommentares/_form.html.erb
<%= form_with(model: kommentare) do |form| %>
  <% if kommentare.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kommentare.errors.count, "error") %> prohibited this kommentare from being saved:</h2>

      <ul>
        <% kommentare.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :posts_id, style: "display: block" %>
    <%= form.text_field :posts_id %>
  </div>

  <div>
    <%= form.label :zeit, style: "display: block" %>
    <%= form.datetime_field :zeit %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kommentares/_kommentare.html.erb
<div id="<%= dom_id kommentare %>">
  <p>
    <strong>Posts:</strong>
    <%= kommentare.posts_id %>
  </p>

  <p>
    <strong>Zeit:</strong>
    <%= kommentare.zeit %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= kommentare.text %>
  </p>

</div>

app/views/kommentares/edit.html.erb
<h1>Editing kommentare</h1>

<%= render "form", kommentare: @kommentare %>

<br>

<div>
  <%= link_to "Show this kommentare", @kommentare %> |
  <%= link_to "Back to kommentares", kommentares_path %>
</div>

app/views/kommentares/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Kommentares</h1>

<div id="kommentares">
  <% @kommentares.each do |kommentare| %>
    <%= render kommentare %>
    <p>
      <%= link_to "Show this kommentare", kommentare %>
    </p>
  <% end %>
</div>

<%= link_to "New kommentare", new_kommentare_path %>

app/views/kommentares/new.html.erb
<h1>New kommentare</h1>

<%= render "form", kommentare: @kommentare %>

<br>

<div>
  <%= link_to "Back to kommentares", kommentares_path %>
</div>

app/views/kommentares/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kommentare %>

<div>
  <%= link_to "Edit this kommentare", edit_kommentare_path(@kommentare) %> |
  <%= link_to "Back to kommentares", kommentares_path %>

  <%= button_to "Destroy this kommentare", @kommentare, method: :delete %>
</div>